# Generated by Django 5.1.2 on 2024-11-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_college_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
