# Generated by Django 5.1.2 on 2024-11-10 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_facility_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='facilities',
        ),
        migrations.AddField(
            model_name='facility',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='api.college'),
        ),
    ]
