# Generated by Django 5.1.2 on 2024-11-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_college_facilities_facility_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='college',
        ),
        migrations.AddField(
            model_name='college',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='colleges', to='api.facility'),
        ),
    ]
