# Generated by Django 5.1.2 on 2024-11-11 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_facility_college_college_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='name',
        ),
    ]
