# Generated by Django 5.1.2 on 2024-11-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='name',
            field=models.CharField(default='Unnamed Facility', max_length=255),
            preserve_default=False,
        ),
    ]
