# Generated by Django 5.1.2 on 2024-11-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_facility_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(default='Unnamed Facility', max_length=255),
        ),
    ]
