# Generated by Django 5.1.2 on 2024-11-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='years',
            field=models.IntegerField(default=0),
        ),
    ]
