# Generated by Django 5.1.2 on 2024-11-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_course_semester_course_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='facilities',
        ),
    ]
