# Generated by Django 5.1.2 on 2024-11-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_college_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce'), ('engineering', 'Engineering'), ('management', 'Management'), ('medical', 'Medical'), ('Pharmacy', 'pharmacy'), ('law', 'Law'), ('agriculture', 'Agriculture'), ('paramedical', 'Paramedical'), ('design', 'Design'), ('allied health science', 'Allied Health Science'), ('veterinary', 'Veterinary')], default='science', max_length=50),
        ),
    ]
