# Generated by Django 5.1.3 on 2024-12-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_college_approval_college_logo_college_ownership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
            ],
        ),
    ]
