# Generated by Django 5.1.3 on 2024-12-19 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_selectedwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_courses', to='api.college')),
            ],
        ),
        migrations.DeleteModel(
            name='SelectedWords',
        ),
        migrations.RemoveField(
            model_name='course',
            name='college',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fees',
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_courses', to='api.course'),
        ),
        migrations.AlterUniqueTogether(
            name='collegecourse',
            unique_together={('course', 'college')},
        ),
    ]
