# Generated by Django 5.1.2 on 2024-12-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
