# Generated by Django 5.1.2 on 2025-01-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_inquiry_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
